### ISSUE TITLE
Eye Candy- 'Experimental Stars' not worrking

### ISSUE THREAD

**Issue by austinrojers** [JezerM/Aether#4]
Eye Candy- 'Experimental Stars' in the _Style_ tab, giving errors

![Screenshot from 2022-01-07 07-33-11](https://user-images.githubusercontent.com/87067093/148479481-c442f732-d9ba-4de5-afdd-57550c45f8c0.png)
```

austin@austin-Inspiron-15-3567:~$ nody-greeter 
2022-01-07 07:32:48 [ DEBUG ] browser.js 121: Initializing Browser Window
2022-01-07 07:32:48 [ DEBUG ] browser.js 137: Browser Window created
2022-01-07 07:32:48 [ DEBUG ] screensaver.js 39: Screensaver set
2022-01-07 07:32:48 [ DEBUG ] browser.js 118: Theme loaded
2022-01-07 07:32:48 [ DEBUG ] bridge.js 65: LightDM API connected
2022-01-07 07:32:48 [ DEBUG ] globals.js 15: Javascript logger is ready
2022-01-07 07:32:48 [ DEBUG ] globals.js 12: Window is ready
2022-01-07 07:32:49 [ DEBUG ] browser.js 155: Nody Greeter started
2022-01-07 07:32:58 [ WARN ] web-greeter://app/usr/share/web-greeter/themes/aether/dist/js/Aether.js 2:     at new t (web-greeter://app/usr/share/web-greeter/themes/aether/dist/js/Aether.js:2:690289)
    at Function.t.create (web-greeter://app/usr/share/web-greeter/themes/aether/dist/js/Aether.js:2:692648)
    at web-greeter://app/usr/share/web-greeter/themes/aether/dist/js/Aether.js:2:707062
    at new e (web-greeter://app/usr/share/web-greeter/themes/aether/dist/js/Aether.js:2:707072)
    at a.value (web-greeter://app/usr/share/web-greeter/themes/aether/dist/js/Aether.js:2:913038)
    at ss (web-greeter://app/usr/share/web-greeter/themes/aether/dist/js/Aether.js:2:197635)
    at vl (web-greeter://app/usr/share/web-greeter/themes/aether/dist/js/Aether.js:2:215261)
    at t.unstable_runWithPriority (web-greeter://app/usr/share/web-greeter/themes/aether/dist/js/Aether.js:2:256038)
2022-01-07 07:32:59 [ ERROR ] web-greeter://app/usr/share/web-greeter/themes/aether/dist/js/Aether.js 2: Uncaught TypeError: Pf.fromImage is not a function
2022-01-07 07:34:32 [ DEBUG ] screensaver.js 54: Screensaver reset

```

**Comment by JezerM** [comment]
Yeah, that's why it's experimental, and I don't expect to work on it soon.

**Comment by austinrojers** [comment]
I was just asking cause it already works in Noisek’s original project

**Comment by JezerM** [comment]
Hmm, I could give a look at it, but don't expect so much xd

At least, I could mitigate the errors.

**Comment by austinrojers** [comment]
It’s not at all a big issue, I was just pointing it out.

**Comment by austinrojers** [comment]
Thanks a lot @JezerM!
