### ISSUE TITLE
Some errors

### ISSUE THREAD

**Issue by austinrojers** [JezerM/Aether#6]
Hey there, @JezerM. How are you? It's been a long time!
I am using Linux Mint Cinnamon right now, so I installed your nody-greeter!
Here are some errors I encountered.
The first one doesn't seem to be significant, as the greeter works on logging out.(It also happens with web-greeter)
But the second one seems to be a bug.

```
 nody-greeter 
2022-12-30 14:01:17 [ DEBUG ] browser.js 121: Initializing Browser Window
2022-12-30 14:01:17 [ DEBUG ] browser.js 137: Browser Window created
2022-12-30 14:01:17 [ DEBUG ] screensaver.js 39: Screensaver set
2022-12-30 14:01:17 [ DEBUG ] browser.js 118: Theme loaded

2022-12-30 14:01:17 [ ERROR ] bridge.js 50: Error: Unable to determine socket to daemon

2022-12-30 14:01:17 [ DEBUG ] bridge.js 65: LightDM API connected
2022-12-30 14:01:17 [ DEBUG ] globals.js 15: Javascript logger is ready
2022-12-30 14:01:17 [ DEBUG ] globals.js 12: Window is ready
2022-12-30 14:01:26 [ DEBUG ] browser.js 155: Nody Greeter started

2022-12-30 14:01:28 [ ERROR ] web-greeter://app/usr/share/web-greeter/themes/Aether/dist/js/Aether.js 2: Uncaught (in promise) TypeError: Cannot read property 'split' of null

2022-12-30 14:01:38 [ DEBUG ] screensaver.js 54: Screensaver reset

```

**Comment by JezerM** [comment]
Hi, sorry for the delay (I was playing Minecraft xd). I will try to fix it soon.

**Comment by austinrojers** [comment]
no worries

**Comment by JezerM** [comment]
@austinrojers, could you try to run this theme in debug mode and show the Developer Tools console (`Ctrl+Shift+I`)? Also, what do you do to fire this error?

**Comment by austinrojers** [comment]
This is my latest output of the terminal when I run nody-greeter:
```
 nody-greeter 
2023-01-18 10:32:03 [ WARN ] config.js 224: Theme config was not loaded:

	Error: ENOENT: no such file or directory, open '/usr/share/web-greeter/themes/Aether/index.yml'

2023-01-18 10:32:03 [ DEBUG ] config.js 225: Using default theme config
2023-01-18 10:32:03 [ DEBUG ] browser.js 125: Initializing Browser Window
2023-01-18 10:32:03 [ DEBUG ] browser.js 177: Browser Window created
2023-01-18 10:32:03 [ DEBUG ] screensaver.js 42: Screensaver set
2023-01-18 10:32:03 [ DEBUG ] browser.js 122: Theme loaded
2023-01-18 10:32:03 [ DEBUG ] globals.js 16: Javascript logger is ready
2023-01-18 10:32:03 [ DEBUG ] globals.js 13: Window is ready

2023-01-18 10:32:03 [ ERROR ] bridge.js 53: Error: Unable to determine socket to daemon
    at new Greeter (/opt/nody-greeter/resources/app.asar/js/bridge/bridge.js:49:28)
    at Function.getInstance (/opt/nody-greeter/resources/app.asar/js/bridge/bridge.js:99:52)
    at /opt/nody-greeter/resources/app.asar/js/bridge/bridge.js:718:37
[28422:0118/103203.713835:ERROR:browser_main_loop.cc(269)] <unknown>: lightdm_greeter_ensure_shared_data_dir_sync: assertion 'priv->connected' failed

2023-01-18 10:32:03 [ DEBUG ] bridge.js 70: LightDM API connected

[28456:0118/103204.954043:ERROR:sandbox_linux.cc(376)] InitializeSandbox() called with multiple threads in process gpu-process.

2023-01-18 10:32:05 [ DEBUG ] browser.js 198: Nody Greeter started win: 2785062953156673
2023-01-18 10:32:21 [ DEBUG ] screensaver.js 58: Screensaver reset

```
The errors are different now.
I had updated web-greeter and nody-greeter recently.

![image](https://user-images.githubusercontent.com/87067093/213088912-d721ebae-0ddd-4577-81cc-9ea80c9b8af2.png)

Is this what you wanted?

**Comment by austinrojers** [comment]
Previously, when I opened this issue, I could not change the distro icons. 
Now that issue seemed to have gone.
As I have mentioned above, the debug output has changed now.

Cheers!

**Comment by JezerM** [comment]
> Is this what you wanted?

Yeah, thanks.

However, it seems the issue is gone? The only error you have: `Error: Unable to determine socket to daemon` is because your xsession desktop file does not allow LightDM with `X-LightDM-Allow-Greeter=true`. You could try to add the previous line to your desktop file at `/usr/share/xsessions/` and try again~

**Comment by austinrojers** [comment]
Yup adding `X-LightDM-Allow-Greeter=true` to `/usr/share/xsessions/` fixed it! 

What about `Error: ENOENT: no such file or directory, open '/usr/share/web-greeter/themes/Aether/index.yml'`?

Thanks

**Comment by JezerM** [comment]
> What about Error: ENOENT: no such file or directory, open '/usr/share/web-greeter/themes/Aether/index.yml'?

It's nothing to worry about. The `index.yml` file is used to define which HTML file to use for multi-monitor support, but there is no issue if it's missing.
